name: Deploy

on:
  # events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  #push:
  pull_request:
    types: 
      - closed
    branches:
    - master   
  push:
    branches:
    - develop

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:  
          node-version: '16'
  #    - name: Configure AWS Credentials  
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy server
        run: |
          npm install
          npm install -g serverless
          npm install serverless-offline
          serverless config credentials --overwrite --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          serverless deploy --stage ${{ secrets.DEV_ENV }}
  #    - name: install typescript
  #      run: |
  #        npm i -g typescript
  #    - name: install dependencies
  #      run: |
  #        npm i
  #    - name: copy folder
  #      run: |
  #        cp -r ./node_modules ./deploy
  #        cp ./package.json ./deploy
  #    - name: list files
  #      run: |
  #        ls ./deploy/
  #    - name: deploy to AWS lambda
  #      run: |
  #        zip -j deploy.zip ./deploy/* 
  #        aws lambda update-function-code --function-name=test_backend --zip-file=fileb://deploy.zip 