name: Deploy

on:
  # events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  #push:
  pull_request:
    types: 
      - closed
    branches:
    - master   

jobs:
  if_merged:
  #deploy_lambda:
    runs-on: ubuntu-latest
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v2  # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:  
          node-version: '16' #--> Specify the Version of the Node 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} #--> Define Region of the AWS-CLI 
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
          npm run install -g typescript
          tsc
          npm run install
          cp -r ./node_modules ./.build
      - name: deploy
        #--> Zip the Code As we know lambda function accept the zip file.
        run: |
          zip -j deploy.zip ./.build/* 
          aws lambda update-function-code --function-name=${{ secrets.AWS_FUNCTION_NAME }} --zip-file=fileb://deploy.zip 